
version: 2

models:
  - name: dim_vinhome
    description: "Final Cleaned VinHome Data"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: price
        tests:
          - not_null
          - positive_value
      - name: icon_url
        tests:
          - valid_url

  - name: dim_vinfast
    description: "Final Cleaned VinFast Data"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: price
        tests:
          - not_null
          - positive_value
      - name: icon_url
        tests:
          - valid_url
